import secrets
from itertools import count

from users.models import User


_username_counter = count()


def _unique_suffix():
    return next(_username_counter)


def _default_username():
    return f"user{_unique_suffix()}"


def _default_email():
    return f"{_default_username()}@example.com"


def _default_password():
    return secrets.token_urlsafe(12)


def _default_name():
    return "Test User"


def _default_description():
    return "Autogenerated user for tests"


def create_account(username=None, email=None, password=None, name=None, **kwargs):
    """Create a test account with predictable defaults."""

    email = email or _default_email()
    username = username or email.split("@")[0]
    password = password or _default_password()
    name = name or _default_name()

    description = kwargs.get("description") or _default_description()
    is_superuser = kwargs.get("is_superuser") or False
    is_manager = kwargs.get("is_manager") or False
    is_editor = kwargs.get("is_editor") or False

    user = User.objects.create(
        username=username,
        email=email,
        name=name,
        description=description,
        is_superuser=is_superuser,
        is_staff=is_superuser,
        is_editor=is_editor,
        is_manager=is_manager,
    )

    user.set_password(password)
    user.save()
    return user
